apiVersion: v1
kind: Service
metadata:
  name: unbound-internal
  labels:
    {{- include "unbound-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: dns-udp
      protocol: UDP
      name: dns-udp
    - port: {{ .Values.service.port }}
      targetPort: dns-tcp
      protocol: TCP
      name: dns-tcp
  selector:
    {{- include "unbound-chart.selectorLabels" . | nindent 4 }}
